### ISSUE TITLE
Cannot use 'environment' as a key in the configuration json

### ISSUE THREAD

**Issue by pdenny** [ResourceDataInc/Centroid#73]
It was not clear to me that I could not use the word "environment" as a key in my configuration json. It might be worth including that in the documentation.

I'm not sure if this is the case for ruby or python, but it certainly is for C#. The way it manifests itself is by completely ignoring sections named "environment"

**Comment by jtroe** [comment]
This is because the `environment` property spits back which environment the config was gen'd from if processed with `for_environment`.

I shall ponder on this issue.
